services:
  colabboard.web:
    image: colabboard.web
    build:
      context: .
      dockerfile: ColabBoard.Web/Dockerfile
    ports:
      - "8080:8080"  
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - colabboard-network

  postgresdb:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pisyapopakaka
      POSTGRES_DB: ColabBoardDb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d ColabBoardDb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - colabboard-network
  
  colabboard.frontend:
    image: colabboard.frontend
    build:
      context: ../../colabboardfront
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - colabboard.web
    networks:
      - colabboard-network
  
volumes:
  db_data:

networks:
  colabboard-network:
    driver: bridge
    